apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: techfood

resources:
  - namespace.yaml
  - configmaps.yaml
  - secrets.yaml
  - techfood-api.yaml
  # - techfood-admin.yaml
  # - techfood-self-order.yaml
  # - techfood-monitor.yaml
  - techfood-ingress.yaml
  - hpa.yaml
  # - monitoring.yaml
