apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: techfood

resources:
  - namespace.yaml
  - configmaps.yaml
  - secrets.yaml
  # - pvc.yaml  # AWS Academy doesn't support OIDC provider for EBS CSI
  # - techfood-db.yaml
  - techfood-api.yaml
  # - techfood-admin.yaml
  # - techfood-self-order.yaml
  # - techfood-monitor.yaml
  # - techfood-nginx.yaml
  - hpa.yaml
  # - monitoring.yaml
