apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: techfood

resources:
  - namespace.yaml
  - configmaps.yaml
  - secrets.yaml
  - storage.yaml
  - rabbitmq.yaml
  - techfood-order-api.yaml
  - techfood-order-worker.yaml
  - techfood-payment-api.yaml
  - techfood-payment-worker.yaml
  - techfood-backoffice-api.yaml
  - techfood-kitchen-api.yaml
  - techfood-kitchen-worker.yaml
  # - techfood-admin.yaml
  # - techfood-self-order.yaml
  # - techfood-monitor.yaml
  - techfood-ingress.yaml
  - hpa.yaml
  # - monitoring.yaml
